---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy Warfile to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/MyMavenWebApp2/target/MyMavenWebApp2.war"
        dest: "/opt/tomcat/webapps/MyMavenWebApp2.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted


